### ISSUE TITLE
Request for Missing 'tools' Folder

### ISSUE THREAD

**Issue by breakTBB** [h4iku/T5APR#2]
I noticed that the project seems to be missing the 'tools' folder, and when running the code, I encountered a `FileNotFoundError` for the file `/root/T5APR-main/tools/tree-sitter-lib/vendor/tree-sitter-python/src/parser.c`. It appears that the 'tools' folder is necessary for the correct functioning of the code.
Could you please share the missing 'tools' folder or provide instructions on how to obtain it?

**Comment by breakTBB** [comment]
I am currently using [this](https://github.com/tree-sitter)

**Comment by h4iku** [comment]
Hi,
I'll try to complete the code and write some documentation soon. Regarding the `tools` folder, as you've already found out, you just have to follow the [tree-sitter](https://github.com/tree-sitter/py-tree-sitter) instructions to clone the required language grammars.

**Comment by breakTBB** [comment]
> Hi, I'll try to complete the code and write some documentation soon. Regarding the `tools` folder, as you've already found out, you just have to follow the [tree-sitter](https://github.com/tree-sitter/py-tree-sitter) instructions to clone the required language grammars.

Thank you for your willingness to complete the code and provide documentation. Your efforts are greatly appreciated, and this will be extremely valuable for future research work. I look forward to the updated code and documentation.
